# Generated by Django 3.1.1 on 2020-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofunc', '0002_auto_20200911_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
